
$CPAN::Config = {
  'build_cache' => q[10],
  'build_dir' => q[/Users/andy/.cpan/build],
  'cache_metadata' => q[1],
  'cpan_home' => q[/Users/andy/.cpan],
  'dontload_hash' => {  },
  'ftp' => q[/usr/bin/ftp],
  'ftp_proxy' => q[],
  'getcwd' => q[cwd],
  'gpg' => q[/opt/local/bin/gpg],
  'gzip' => q[/opt/local/bin/gzip],
  'histfile' => q[/Users/andy/.cpan/histfile],
  'histsize' => q[100],
  'http_proxy' => q[],
  'inactivity_timeout' => q[0],
  'index_expire' => q[1],
  'inhibit_startup_message' => q[0],
  'keep_source_where' => q[/Users/andy/.cpan/sources],
  'lynx' => q[/opt/local/bin/lynx],
  'make' => q[/usr/bin/make],
  'make_arg' => q[],
  'make_install_arg' => q[],
  'makepl_arg' => q[],
  'ncftp' => q[],
  'ncftpget' => q[],
  'no_proxy' => q[],
  'pager' => q[/usr/bin/less],
  'prerequisites_policy' => q[ask],
  'scan_cache' => q[atstart],
  'shell' => q[/bin/bash],
  'tar' => q[/opt/local/bin/gnutar],
  'term_is_latin' => q[1],
  'unzip' => q[/opt/local/bin/unzip],
  'urllist' => [q[http://cpan.ripley], q[ftp://cpan.etla.org/pub/CPAN], q[ftp://ftp.demon.co.uk/pub/CPAN/], q[ftp://ftp.flirble.org/pub/CPAN/], q[ftp://ftp.mirror.ac.uk/sites/ftp.funet.fi/pub/languages/perl/CPAN/], q[ftp://ftp.mirror.anlx.net/CPAN/]],
  'wget' => q[/opt/local/bin/wget],
};
1;
__END__
