#!/bin/bash

if [[ -d $HOME/.pyenv ]]; then
  export PYENV_ROOT="$HOME/.pyenv"
  export PIPX_DEFAULT_PYTHON="$PYENV_ROOT/shims/python"
  [[ -d $PYENV_ROOT/bin ]] && PATH="$PYENV_ROOT/bin:$PATH"
  eval "$(pyenv init -)"
  # eval "$(pyenv virtualenv-init -)"
fi

# vim:ts=2:sw=2:sts=2:et:ft=sh
