#!/bin/sh
if [ -f ~/.Xauthority ]
then
    if [ -n "$SSH_CLIENT" ]
    then
        remote=`echo $SSH_CLIENT | cut -d' ' -f1`
        auth="/tmp/$remote.Xauth"
        if scp -q -o PasswordAuthentication=no $remote:~/.Xauthority $auth && [ -s $auth ]
        then
            xauth merge $auth
            export DISPLAY=$remote:0.0      
            echo "Remote X server is $DISPLAY"
            rm -f $auth
        fi
    fi
fi
