#!perl

%ColourMap = (
  green => [
    qr{(\[INFO\]\s+BUILD SUCCESSFUL)},
    qr{((?:Failures|Errors|Skipped):\s+0)},
  ],
  red => [
    qr{(\[ERROR\].*)},
    qr{(\[INFO\]\s+BUILD FAILURE)},
    qr{((?:Failures|Errors):\s+[1-9]\d*)},
    qr{(FAILURE!)},
  ],
  yellow => [
    qr{(\[WARNING\].*)}, qr{(Skipped:\s+[1-9]\d*)},
    qr{(Tests\s+run:\s+0\s+.*)},
  ],
);

1;

# vim:ts=2:sw=2:sts=2:et:ft=perl
