#!/usr/bin/env perl
# vim:ts=2:sw=2:sts=2:et:ft=perl

use strict;
use warnings;
use File::Basename;

die "syntax: c <name> <ext>\n" unless @ARGV == 2;
my ( $name, $ext ) = @ARGV;

my @body = ();
push @body, 'printf( "Hello, World\n" );' if $name eq 'hello.c';
my $body = join '', map "  $_\n", @body;

print <<EOT;
/* $name */

#include <stdio.h>

int main( void )
{
$body  return 0;
}

/* vim:ts=2:sw=2:sts=2:et:ft=c 
 */
EOT

